### ISSUE TITLE
NullPointer Exception while writing schemaless json data to HBase

### ISSUE THREAD

**Issue by nishutayal** [nishutayal/kafka-connect-hbase#5]
Whenever a schemaless json(without Schema and payload) is available in kafka topic and connector tries to write, it throws Null Pointer Exception.

> Caused by: java.lang.NullPointerException
>         at org.apache.hadoop.hbase.client.Put.<init>(Put.java:68)
>         at org.apache.hadoop.hbase.client.Put.<init>(Put.java:58)
>         at io.svectors.hbase.util.ToPutFunction.apply(ToPutFunction.java:82)
> 

Input json example : `{"id" : 1, "name" : "Test"}`

**Comment by karthit** [comment]
@nishutayal 
I've pulled a latest verson from confluent-hub, i'm still getting this error for schema-less json
