### ISSUE TITLE
NullPointerException when I use this Skin to hbase

### ISSUE THREAD

**Issue by Loernl** [nishutayal/kafka-connect-hbase#9]
my config is :
    "connector.class": "io.svectors.hbase.sink.HBaseSinkConnector",
    "tasks.max": "1",
    "topics": "avro",
    "zookeeper.quorum": "localhost:2181",
    "hbase.avro.family":"info",
    "hbase.avro.rowkey.columns":"id",
    "hbase.avro.rowkey.delimiter":"|",
    "event.parser.class":"io.svectors.hbase.parser.AvroEventParser"

my producer data is :
   {"value_schema_id": 123, "records": [{"value": {"id": 3, "name":"abc", "age": 111}}]}
I run this task,hava a problem like this:

java.lang.NullPointerException

t org.apache.hadoop.hbase.client.Put.<init>(Put.java:68)

t org.apache.hadoop.hbase.client.Put.<init>(Put.java:58)

t io.svectors.hbase.util.ToPutFunction.apply(ToPutFunction.java:73)

t io.svectors.hbase.sink.HBaseSinkTask.lambda$null$0(HBaseSinkTask.java:77)

t java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

t java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)

t java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

t java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

t java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)

t java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

t java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)

t io.svectors.hbase.sink.HBaseSinkTask.lambda$put$1(HBaseSinkTask.java:77)

t java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)

t java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)

t java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)

t java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

t java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

t java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)

t java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

t java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)

t io.svectors.hbase.sink.HBaseSinkTask.put(HBaseSinkTask.java:76)

t org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)

t org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)

t org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)

t org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)

t org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)

t org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)

t java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

t java.util.concurrent.FutureTask.run(FutureTask.java:266)

t java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

t java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

t java.lang.Thread.run(Thread.java:748)

[2019-03-15 02:08:12,046] ERROR WorkerSinkTask{id=hbase-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)

org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.

t org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)

t org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)

t org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)

t org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)

t org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)

t org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)

t java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

t java.util.concurrent.FutureTask.run(FutureTask.java:266)

t java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

t java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

t java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.NullPointerException

t org.apache.hadoop.hbase.client.Put.<init>(Put.java:68)

t org.apache.hadoop.hbase.client.Put.<init>(Put.java:58)

t io.svectors.hbase.util.ToPutFunction.apply(ToPutFunction.java:73)

t io.svectors.hbase.sink.HBaseSinkTask.lambda$null$0(HBaseSinkTask.java:77)

t java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

t java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)

t java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

t java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

t java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)

t java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

t java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)

t io.svectors.hbase.sink.HBaseSinkTask.lambda$put$1(HBaseSinkTask.java:77)

t java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)

t java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)

t java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)

t java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

t java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

t java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)

t java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

t java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)

t io.svectors.hbase.sink.HBaseSinkTask.put(HBaseSinkTask.java:76)

t org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)

**Comment by nishutayal** [comment]
I have tried to offload avro data into hbase table, works fine for me with the same code. 
Can you share the connect properties file? Did you make sure that data is written in proper avro format?

**Comment by Loernl** [comment]
I find the reason for this,but when i start the task ,connect to the hbase region server,the server will be  shut down.can you give me your test config,thanks

**Comment by nishutayal** [comment]
Have you added hbase-site.xml config in your jar?   Here is the connect config, I used:

> bootstrap.servers=localhost:9092
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/data/connect.offsets
offset.flush.interval.ms=10000
plugin.path=/share/java,/data/personal/oss

**Comment by Loernl** [comment]
yes,I add the xml for hbase config,it's ok.I am wondering if hbase and connect must be on the same machine.when i connect to the remote hbase ,the connect will reminder me connectException,the remote hbase origin server will be down.I don't know what the reason is. Could you please help to answer thanks.

**Comment by nishutayal** [comment]
No, it is not necessary at all to have connect and hbase on the same machine. Connect needs to know the HBase cluster IP address. As long as you have network access from between connect machine and HBase cluster, it will work.

**Comment by Loernl** [comment]
ok,thanks
